version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'meowtobot/challenge'
    networks:
      - stack
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=challenge
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13
    networks:
      - stack
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

networks:
  stack:
    driver: bridge