version: '3.9'

services:
  fluentd:
    image: fluent/fluentd:v1.16-1
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/log:/fluentd/log
    command: [ "fluentd", "-c", "/fluentd/etc/fluent.conf" ]

  server:
    image: 'challenge-1.0.0.jar'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=challenge
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "fluentd:24224"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
