apiVersion: 1

datasources:
  - access: proxy
    basicAuth: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    editable: true
    isDefault: true
    name: loki
    type: loki
    uid: loki
    url: http://127.0.0.1:3100
    version: 1